# Server Configuration
spring.application.name=${APP_NAME}
server.port=${SERVER_PORT}

# Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
<<<<<<< HEAD
<<<<<<< HEAD
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/Port-Management-Sytem-DB
spring.datasource.username=postgres
spring.datasource.password=Ankit@123
>>>>>>> 63b09c8 (refined the login and logout)
=======
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
>>>>>>> 6532aa5 (updated the application properties and env segment)

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
<<<<<<< HEAD
<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL}
=======
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
>>>>>>> 63b09c8 (refined the login and logout)
=======
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL}
>>>>>>> 6532aa5 (updated the application properties and env segment)
