package com.portmanagement.backend.service.impl;

import com.portmanagement.backend.dto.AdministratorLoginRequest;
import com.portmanagement.backend.dto.AdministratorResponse;
import com.portmanagement.backend.dto.AdministratorSignupRequest;
import com.portmanagement.backend.entity.Administrator;
import com.portmanagement.backend.repository.AdministratorRepository;
import com.portmanagement.backend.service.AdministratorService;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpSession;
import lombok.RequiredArgsConstructor;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
@Service
@RequiredArgsConstructor
public class AdministratorServiceImpl implements AdministratorService {

    private final AdministratorRepository administratorRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    @Transactional
    public AdministratorResponse registerAdministrator(AdministratorSignupRequest request) {
        if (administratorRepository.existsByEmail(request.getEmail())) {
            throw new IllegalArgumentException("Email is already registered: " + request.getEmail());
        }

        String autoGeneratedEmployeeId = generateSequentialEmployeeId();

        Administrator administrator = Administrator.builder()
                .fullName(request.getFullName())
                .employeeId(autoGeneratedEmployeeId)
                .email(request.getEmail())
                .password(passwordEncoder.encode(request.getPassword()))
                .phoneNumber(request.getPhoneNumber())
                .designation(request.getDesignation())
                .department(request.getDepartment())
                .role("ADMIN")
                .active(true)
                .build();

        Administrator savedAdmin = administratorRepository.save(administrator);

        return mapToResponse(savedAdmin);
    }

    @Override
    @Transactional(readOnly = true)
    public AdministratorResponse loginAdministrator(AdministratorLoginRequest request, HttpServletRequest httpServletRequest) {
        String identifier = request.getIdentifier().trim();

        Administrator administrator = administratorRepository
                .findByEmailIgnoreCaseOrEmployeeIdIgnoreCase(identifier, identifier)
                .orElseThrow(() -> new BadCredentialsException("Invalid credentials"));

        if (!passwordEncoder.matches(request.getPassword(), administrator.getPassword())) {
            throw new BadCredentialsException("Invalid credentials");
        }

        if (!administrator.isActive()) {
            throw new IllegalArgumentException("Administrator account is inactive");
        }

        HttpSession session = httpServletRequest.getSession(true);
        session.setAttribute("ADMINISTRATOR_ID", administrator.getId());
        session.setAttribute("ADMINISTRATOR_ROLE", administrator.getRole());

        return mapToResponse(administrator);
    }

    @Override
    public void logoutAdministrator(HttpServletRequest request) {
        HttpSession session = request.getSession(false);
        if (session != null) {
            session.invalidate();
        }
    }

    private synchronized String generateSequentialEmployeeId() {
        return administratorRepository.findTopByOrderByIdDesc()
                .map(lastAdmin -> {
                    try {
                        long lastIdNumber = Long.parseLong(lastAdmin.getEmployeeId());
                        return String.format("%07d", lastIdNumber + 1);
                    } catch (NumberFormatException e) {
                        return String.format("%07d", 1000000L + lastAdmin.getId() + 1);
                    }
                })
                .orElse("1000001");
    }

    private AdministratorResponse mapToResponse(Administrator admin) {
        return AdministratorResponse.builder()
                .id(admin.getId())
                .fullName(admin.getFullName())
                .employeeId(admin.getEmployeeId())
                .email(admin.getEmail())
                .phoneNumber(admin.getPhoneNumber())
                .designation(admin.getDesignation())
                .department(admin.getDepartment())
                .role(admin.getRole())
                .active(admin.isActive())
                .build();
    }
}
